# Generated by Django 6.0.3 on 2026-03-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead / Manager')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='key_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source_label',
            field=models.CharField(default='Portal', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='workplace_type',
            field=models.CharField(choices=[('on-site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='on-site', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('software-development', 'Software Development (Coding Jobs)'), ('web-design', 'Web & Design'), ('database-backend', 'Database & Backend'), ('data-ai', 'Data & AI Jobs'), ('cybersecurity', 'Cybersecurity'), ('cloud-devops', 'Cloud & DevOps'), ('networking-systems', 'Networking & System Jobs'), ('testing-qa', 'Testing & QA')], max_length=100),
        ),
    ]
